/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ManagerApp_handler_GetADdata */

#ifndef _Included_com_ManagerApp_handler_GetADdata
#define _Included_com_ManagerApp_handler_GetADdata
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ManagerApp_handler_GetADdata
 * Method:    GetData
 * Signature: (Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_ManagerApp_handler_GetADdata_GetData
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
